# Generated by Django 3.0.5 on 2020-06-19 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseTypeName', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'exercisetypes',
                'db_table': 'exercisetype',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseName', models.CharField(max_length=255)),
                ('exerciseDate', models.DateField()),
                ('exerciseDurationMinutes', models.SmallIntegerField()),
                ('exerciseNotes', models.TextField(blank=True, null=True)),
                ('exerciseType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eapp.ExerciseType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'exercises',
                'db_table': 'exercise',
            },
        ),
    ]
